config/routes.rb
Rails.application.routes.draw do
  
  
  get 'events/index'
  root to: 'practices#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :users,only: [:show,:edit,:update,:destroy] do
    resources :events,only:[:index,:create,:destroy]
    resources :relationships,only:[:create,:destroy]
    resources :chat_rooms,only:[:index,:create,:show] do
      resources :chat_messages,only:[:create]
    end
  end
  resources :notifications,only: [:index] do
    collection do
      delete "destroy_all"
    end
  end
  resources :practices do
    resources :likes, only: [:create, :destroy]
    resources :pcomments, only: [:create, :destroy]
    collection do
      get "rank"
      get "ptaglist"
      get "search"
    end
  end

  resources :games,only:[:index,:new,:create,:destroy,:show] do 
      member do
        post "challenge"
      end
  end

  

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    @other_user = User.find(params[:user_id])
    following = current_user.follow(@other_user)
    if following.save
      flash[:notice] = "#{@other_user.name}をフォローしました"
      @other_user.create_notification_follow!(current_user) # フォローと同時に、フォローした通知を登録
      @relation = Relationship.find_by(user_id: current_user.id, follow_id: @other_user.id)
    else
      flash[:alert] = 'フォローに失敗しました'
    end
  end

  def destroy
    @other_user = User.find(params[:user_id])
    following = current_user.unfollow(@other_user)
    if following.destroy
      flash[:notice] = "#{@other_user.name}フォローを解除しました"
    else
      flash.now[:alert] = 'フォロー解除に失敗しました'
    end
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow.html.erb
  <%=link_to "フォロー",user_relationships_path(user), method: :post,id: "f-btn",class: "btn btn-outline-primary" ,remote:true %>
  <%= link_to "DMする", user_chat_rooms_path(user), method: :post, class: "btn btn-outline-success" %>

app/views/relationships/_unfollow.html.erb
<%=link_to "フォロー解除",user_relationship_path(user,relation), method: :delete,id: "f-btn",class: "btn btn btn-outline-danger",remote:true %>
<%= link_to "DMする", user_chat_rooms_path(user), method: :post, class: "btn btn-outline-success" %>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= j(render partial: "relationships/unfollow" ,locals: {user:@other_user,relation:@relation}) %>");

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= j(render partial: "relationships/follow" ,locals: {user:@other_user}) %>");