config/routes.rb
Rails.application.routes.draw do
  
  
  get 'events/index'
  root to: 'practices#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :users,only: [:show,:edit,:update,:destroy] do
    resources :events,only:[:index,:create,:destroy]
    resources :relationships,only:[:create,:destroy]
    resources :chat_rooms,only:[:index,:create,:show] do
      resources :chat_messages,only:[:create]
    end
  end
  resources :notifications,only: [:index] do
    collection do
      delete "destroy_all"
    end
  end
  resources :practices do
    resources :likes, only: [:create, :destroy]
    resources :pcomments, only: [:create, :destroy]
    collection do
      get "rank"
      get "ptaglist"
      get "search"
    end
  end

  resources :games,only:[:index,:new,:create,:destroy,:show] do 
      member do
        post "challenge"
      end
  end

  

end

app/views/partial/_backmenu.html.erb
<nav class="mobile-menu"><%# ハンバーガーメニュー中身（裏側に設置）%>
  <ul class="mobile-menu__main">
   <%if user_signed_in?%>
        <li class="mobile-menu__item">
          <%= link_to "マイページ",user_path(current_user),class: "main-title"%>
        </li>
        <li class="mobile-menu__item">
          <%=link_to "投稿する",new_practice_path,class: "main-title"%>
        </li>
        <li class="mobile-menu__item">
          <%=link_to "試合募集",games_path,class: "main-title"%>
        </li>
        <li class="mobile-menu__item">
          <%= link_to "通知一覧",notifications_path,class: "main-title"%>
        </li>
        <li class="mobile-menu__item">
          <%= link_to "メッセージ一覧",user_chat_rooms_path(current_user),class: "main-title"%>
        </li>
        <li class="mobile-menu__item">
          <%= link_to "ログアウト",destroy_user_session_path,method: :delete,class: "main-title"%>
        </li>
   <%else%>
      <li class="mobile-menu__item">
        <%= link_to "新規登録",new_user_registration_path,class: "main-title"%>
      </li>
      <li class="mobile-menu__item">
        <%= link_to "ログイン",new_user_session_path,class: "main-title"%>
      </li>
      <li class="mobile-menu__item">
        <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post ,class: "main-title"%>
      </li>
   <%end%> 
  </ul>
</nav>

app/views/partial/_chat_message.html.erb
<div class="chat-message">
  <%if chat_message.user_id==current_user.id%>
    <div class="my_message_box">
      <div class="my_message">
        <%= chat_message.content %>
      </div>
    </div>
      <%if chat_message.check==true%>
        <div class="check_message">
          既読
        </div>
      <%end%>
  <%else%>
    <div class="otheruser_message_box">
      <div class="other_message">
        <%= chat_message.content %>
        </div>
    </div>  
    
  <%end%> 
</div>

app/views/partial/_chat_room_form.html.erb
<%= link_to(user_chat_rooms_path(chat_room_user.user),method: :post,class: "link_decoration") do %>
<div class="tweet_box">
  <div class=friend>
    <div class="friend__info">
       <div class="friend__img">
          <%if chat_room_user.user.myphoto.attached?%>
             <%= image_tag chat_room_user.user.myphoto, class: "smround-img" %>
          <%else%>
              <%= image_tag '/default_myphoto.png' ,class: "smround-img"%>
          <%end%>
       </div>
       <div>
      
       </div>
       
       
       <div class="friend__name">
         <%=chat_room_user.user.name%>
       </div>
    </div>

       <%if chat_messages.where(chat_room_id:chat_room_user.chat_room_id,user_id:chat_room_user.user_id,check:false).exists?%>
         <div class="chat_notification">
            <%=chat_messages.where(chat_room_id:chat_room_user.chat_room_id,user_id:chat_room_user.user_id,check:false).length%>
         </div>
       <%end%>
  </div>
</div>
<%end%>

app/views/partial/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <%# <h2>
      <%= I18n.t("errors.messages.not_saved",count: resource.errors.count,resource: resource.class.model_name.human.downcase)%>
    <%#</h2> %>
    
    <ul style="list-style=">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/partial/_flash.html.erb
 <div class="flash">
   <% if flash[:notice] %><%#flashを表示する%>
      <div class="alert alert-info">
        <%= flash[:notice] %>
      </div>
   <% end %>
   <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
   <% end %>
</div>

app/views/partial/_follow_form.html.erb
<%unless current_user.id==user.id%>
  <% if current_user.following?(user)%>
    <%=render partial: "relationships/unfollow" ,locals:{user:user,relation:relation}%>
  <%else%>
    <%=render partial: "relationships/follow" ,locals:{user:user}%>
  <%end%>
<%end%>

app/views/partial/_friend_index.html.erb
<div class="tweet_box">
  <div class=friend>
    <div class="friend__info">
       <div class="friend__img">
          <%if friend.myphoto.attached?%>
             <%=link_to (image_tag friend.myphoto, class: "smround-img"),user_path(friend)%>
          <%else%>
             <%=link_to (image_tag '/default_myphoto.png' , class: "smround-img"),user_path(friend)%>
          <%end%>
       </div>
       <div class="friend__name">
         <%=friend.name%>
       </div>
    </div>
  </div>
</div>

app/views/partial/_header.html.erb
<header class="header">
  <div class="header__inner appear up">
    <div>
       <%=link_to (image_tag '/soccer_logo.png' ,class:"soccer_logo"),root_path%>
    </div>
    <nav class="header__nav"><%#展開時のメニュー%>
      <ul class="header__ul">
        <%if user_signed_in?%>
          <li class="header__li item">
            <%=link_to("試合募集",games_path)%>
          </li>
          <li class="header__li item">
            <%=link_to("投稿する",new_practice_path)%>
          </li>
          <li class="header__li item">
            <%if unchecked_notifications.any?%>
              <%= link_to(content_tag(:i, '', class: 'far fa-bell fa-lg'),notifications_path)%><span class="notice">●</span>
            <%else%>
              <%= link_to(content_tag(:i, '', class: 'far fa-bell fa-lg'),notifications_path)%>
            <%end%>
          </li>
          <li class="header__li item dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-user-circle fa-lg"></i>   <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%=link_to "マイページ",user_path(current_user),class: "link_decoration"%></li>
              <li><%=link_to "チャット一覧",user_chat_rooms_path(current_user),class: "link_decoration"%></li>
              <li><%=link_to "予定表",user_events_path(current_user),class: "link_decoration"%></li>
              <li><%=link_to "ログアウト",destroy_user_session_path,method: :delete,class: "link_decoration"%></li>
            </ul>
          </li>
        <%else%>
          <li class="header__li item">
            <%=link_to("新規登録",new_user_registration_path)%>
          </li>
          <li class="header__li item">
            <%=link_to("ログイン",new_user_session_path)%>
          </li>
          <li class="header__li item">
            <%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post%>
          </li>
        <%end%>
      </ul>
    </nav>        
    <button class="mobile-menu__btn"><%#ハンーガーメニューボタン%>
      <span></span>
      <span></span>
      <span></span>
    </button>
  </div>  
</header> 
  

app/views/partial/_notifications.html.erb
<%if notification.visiter_id!=notification.visited_id%><%#自分が自分にしたアクションは除く%>
  <% visiter = notification.visiter %>
  <% practice = notification.practice %>
  <div class="notification ">
    <div class="notification__img">
    <%= link_to user_path(notification.visiter) do %>
        <%if notification.visiter.myphoto.attached?%>
          <%= image_tag notification.visiter.myphoto, class: "smround-img" %>
        <%else%>
          <%= image_tag '/default_myphoto.png' ,class: "smround-img"%>
        <%end%>
      <% end %>
    </div>

    <div class="notification__action">
      <%= notification_form(notification) %><span class="moderate-font"><%= " (#{time_ago_in_words(notification.created_at)}前)" %></span>
      <div class="notification__content">
        <% if !@comment.nil? %>
          <p class="moderate-font text-center" style="color: #C0C0C0;"><%= @pcomment %></p> %>
        <% end %>
      </div>
    </div>
  </div>  
<%end%>

app/views/partial/_pcomment_box.html.erb
<div id="render-comments">
  <%=render partial: "pcomments/pcomment",locals:{pcomment:pcomment,practice:practice}%>
</div>

app/views/partial/_practice.html.erb
<div class="tweet_box">

  <div class="tweet_box__user "> <%#投稿上部の投稿者表示%>
    <div class="tweet_user">
      <div class="tweet_user__img">
         <%if practice.user.myphoto.attached?%>
            <%=link_to (image_tag practice.user.myphoto, class: "smround-img"),user_path(practice.user)%>
         <%else%>
            <%=link_to (image_tag '/default_myphoto.png' , class: "smround-img"),user_path(practice.user)%>
         <%end%>
      </div>
      <div class="tweet_user__name">      
            <%=link_to practice.user.name,user_path(practice.user),class:"tweet_name"%>           
      </div>
    </div>
    <%if user_signed_in? && current_user.id==practice.user.id%>
      <div class="gear_icon">
        <i class="fas fa-cog"></i>
      </div>
    <%end%>
      
    <div class="menu">
      <ul class="menu-list">
        <li><%=link_to "編集",edit_practice_path(practice),class:"link_decoration"%></li>        
        <li><%=link_to "削除",practice_path(practice),method: :delete,class:"link_decoration",data: { confirm: '本当に削除しますか?' } %></li>        
      </ul>
    </div>
  </div>
  <%=link_to(practice_path(practice)) do%>
    <%#binding.pry%>
    <div class="tweet_box__img img_black" style="background-image: url(<%= rails_blob_path(practice.images[0]) if practice.images[0].present?%>);"> <%#投稿写真とタイトル%>
      <div class="tweet_title">
        <%=practice.title%>
      </div> 
    </div>
  <%end%>  
  
  <div class="tweet_box__info"><%#投稿についてのミニ情報%>
    <div class="m tag_info">タグ:
      <%practice.ptags.each do |ptag|%>
       <%=ptag.name%>
      <%end%>
      </div>
    <div class="m tweet_box__flex">
      <div id="like-<%=practice.id%>" class="m like_info">
        <%=render partial: 'likes/like',locals: {practice:practice}%>
      </div>
      <div class="m created_at_info"><i class="far fa-clock clock-icon"></i><%= time_ago_in_words(practice.created_at) %>前
      </div>
    </div>
  </div>
  
</div>

app/views/partial/_tweet.html.erb
<div class="tweet_box">
  <div class="tweet_box__user"> <%#投稿上部の投稿者表示%>
    <div class="tweet_user">
      <div class="tweet_user__img">写真</div>
      <div class="tweet_user__name">名前</div>
    </div>
  </div>
  <div class="tweet_box__img"> <%#投稿写真とタイトル%>
    <div class="tweet_title">
      超効率的な中練
    </div>   
  </div>
  <div class="tweet_box__info">
    <div class="tag_info">タグ:中連 効率 最強</div>
    <div class="tweet_box__flex">
      <div class="like_info">いいね: 1  コメント: 2</div>
      <div class="created_at_info">投稿日時:2021年1月1日</div>
    </div>
  </div>
</div>