config/routes.rb
Rails.application.routes.draw do
  
  
  get 'events/index'
  root to: 'practices#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :users,only: [:show,:edit,:update,:destroy] do
    resources :events,only:[:index,:create,:destroy]
    resources :relationships,only:[:create,:destroy]
    resources :chat_rooms,only:[:index,:create,:show] do
      resources :chat_messages,only:[:create]
    end
  end
  resources :notifications,only: [:index] do
    collection do
      delete "destroy_all"
    end
  end
  resources :practices do
    resources :likes, only: [:create, :destroy]
    resources :pcomments, only: [:create, :destroy]
    collection do
      get "rank"
      get "ptaglist"
      get "search"
    end
  end

  resources :games,only:[:index,:new,:create,:destroy,:show] do 
      member do
        post "challenge"
      end
  end

  

end

app/models/game.rb
class Game < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to :user

  belongs_to :gamenum
  belongs_to :gametime
  belongs_to :level

  with_options presence: true do
    validates :gameday
    validates :location, length: { maximum: 30 }
    validates :title, length: { maximum: 40 }
  end

  with_options numericality: { other_than: 1 } do
    validates :gametime_id
    validates :gamenum_id
    validates :level_id
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy, :index]
  before_action :set_game, only: [:show, :challenge, :destroy]
  before_action :are_you_host?, only: [:destroy]

  def index
    @games = Game.includes(:user).order(created_at: 'DESC').where(check: false).page(params[:page]).per(5)
  end

  def show
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      flash[:notice] = '募集に成功しました'
      redirect_to games_path
    else
      flash[:alert] = '募集投稿に失敗しました'
      render :new
    end
  end

  def destroy
    @game.destroy
    flash[:notice] = '募集の削除をしました'
    redirect_to games_path
  end

  def challenge
    @game.check = true
    @game.save
    flash[:notice] = '申し込みを完了しました!!!開催者にDMを送りましょう'
    redirect_to user_path(@game.user_id)
  end

  private

  def game_params
    params.require(:game).permit(:title, :gameday, :location, :gamenum_id, :gametime_id, :level_id,
                                 :description).merge(user_id: current_user.id)
  end

  def set_game
    @game = Game.find(params[:id])
  end

  def recruiting
    redirect_to games_path if @game.check
  end

  def are_you_host?
    redirect_to games_path unless current_user.id == @game.user_id
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<% breadcrumb :game_index%>



<h1 class="page-title">募集掲示板</h1>
<div class="btn-zone center_margin">
      <%= link_to "開催者として募集したい方はこちら",new_game_path%>
</div>
<%@games.each do |game|%>
  <div class="tweet_box">
    <div class="tweet_box__user ">
      <div class="game_title">
      <%=link_to game.title,game_path(game),class:"link_decoration"%>
       
      </div>
    </div>
    <div class="game_info">
      <div class="team_name">主宰：<%=game.user.team_name%></div>
      <div class="location">場所：<%=game.location%></div>
      <div class="gameday">開催日時：<%=game.gameday.strftime("%Y年%m月%d日%H時%M分")%></div>       
    </div>  
  </div>
<%end%>
<div class="pagenation-box">
  <%= paginate @games %>
</div>

app/views/games/new.html.erb
<% breadcrumb :game_new%>

<div class="main">
  <div class="form_box">

  <h1 class="page-title">試合を募集する</h1>
      <%= form_with model: @game, url: games_path(@game),local: true do |f| %>
         <%=render 'partial/error_messages', model: f.object %>

         
        <div class="form-group">
          <label>タイトル</label>
          <%= f.text_field :title, autofocus: true, placeholder: "例：練習試合相手募集！2月21日東京都内", class: "form-control" %>
        </div>

        <div class="form-group">
          <label>日時</label>

          <div class="select-date">
            <%= raw sprintf(f.datetime_select(:gameday, use_month_numbers: true, date_separator: '%s', datetime_separator: '%s'), '年', '月', '日')%>
          </div>
        </div>

        <div class="form-group">
          <label>試合会場</label>
          <%= f.text_field :location, autofocus: true, placeholder: "〇〇市立運動公園", class: "form-control" %>
        </div>

        <div class="form-group">
          <label>1試合の時間</label>
          <%= f.collection_select(:gametime_id, Gametime.all, :id, :name, {}, {class:"select-box"}) %>
        </div>

        <div class="form-group">
          <label>試合本数</label>
          <%= f.collection_select(:gamenum_id, Gamenum.all, :id, :name, {}, {class:"select-box"}) %>
        </div>

        <div class="form-group">
          <label>相手に求めるレベル</label>
          <%= f.collection_select(:level_id, Level.all, :id, :name, {}, {class:"select-box"}) %>
        </div>

        <div class="form-group">
          <label>ご挨拶</label>
          <%= f.text_area :description, autofocus: true, placeholder: "例：来季に向け2年生主体のチームで挑ませていただきます。よろしくお願いします", class: "form-control" %>
        </div>


        <div class="actions">
          <%= f.submit "登録する", id: "submit",class: "btn btn-primary registration-btn" %>
          <p class="warning">※この投稿は後から編集することはできません。本当に募集内容が正しいか確認してください。（削除は可能です）</p>
        </div>
      <% end %>
  </div>
</div>

app/views/games/show.html.erb
<% breadcrumb :game_show, @game %>


<h1 class="page-title">募集詳細</h1>
<div class="tweet_box">
  <div class="tweet_box__user ">
    <div class="game_title">
      <%=@game.title%>
    </div>
  </div>
  <div class="game_info">
    <h5 class="game_show">試合の詳細</h5>
    <div class="game_flex">
      <div>
        <div class="team_name">主宰：<%=@game.user.team_name%></div>
        <div class="location">場所：<%=@game.location%></div>
        <div class="gameday">開催日時：<%=@game.gameday.strftime("%Y年%m月%d日%H時%M分")%></div>       
      </div>
      <div>
        <div class="gameday">試合時間：<%=@game.gametime.name%></div>
        <div class="gameday">試合本数：<%=@game.gamenum.name%></div>
        <div class="gameday">相手に求めているレベル：<%= @game.level.name%></div>
      </div>
    </div>
   
  </div>  
</div>


<h6 class="host-title">開催者からのご挨拶</h6>
<div class="host">

  <div class="host__img">
    <%if @game.user.myphoto.attached?%>
       <%=link_to (image_tag @game.user.myphoto, class: "mdround-img"),user_path(@game.user)%>
    <%else%>
       <%=link_to (image_tag '/default_myphoto.png' , class: "mdround-img"),user_path(@game.user)%>
    <%end%>
  </div>
  <div class="host__greet">
    <%if @game.description==""%>
      この度はご興味を持っていただきありがとうございます。ご応募お待ちしております！！！
    <%else%>
      <%=@game.description%>
    <%end%>
  </div>
  <div class="btn-zone">
    <%= link_to "戻る",games_path, method: :get, class: "btn btn-outline-secondary center_margin" %>
    <%if current_user.id==@game.user_id%>
      <%= link_to "削除",game_path(@game), method: :delete, class: "btn btn-outline-danger center_margin" %>
    <%else%>
      <%= link_to "申込",challenge_game_path(@game),method: :post ,class: "btn btn-outline-success center_margin" %>
    <%end%>
  </div>
</div>