config/routes.rb
Rails.application.routes.draw do
  
  
  get 'events/index'
  root to: 'practices#index'
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :users,only: [:show,:edit,:update,:destroy] do
    resources :events,only:[:index,:create,:destroy]
    resources :relationships,only:[:create,:destroy]
    resources :chat_rooms,only:[:index,:create,:show] do
      resources :chat_messages,only:[:create]
    end
  end
  resources :notifications,only: [:index] do
    collection do
      delete "destroy_all"
    end
  end
  resources :practices do
    resources :likes, only: [:create, :destroy]
    resources :pcomments, only: [:create, :destroy]
    collection do
      get "rank"
      get "ptaglist"
      get "search"
    end
  end

  resources :games,only:[:index,:new,:create,:destroy,:show] do 
      member do
        post "challenge"
      end
  end

  

end

app/models/practice.rb
class Practice < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :pcomments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :practice_ptag_relations, dependent: :destroy
  has_many :ptags, through: :practice_ptag_relations

  has_many :notifications, dependent: :destroy

  belongs_to :user
  belongs_to :hardlevel
  belongs_to :category
  belongs_to :career
  has_many_attached :images

  # with_options presence: true do
  #   validates :title,length:{maximum:25}
  #   validates :content
  # end

  # with_options numericality: { other_than: 1 } do
  #   validates :category_id
  #   validates :hardlevel_id
  # end

  # クラスメソッド,キーワードをもらって検索し、ヒットしたものを返す
  def self.search(keyword)
    if keyword != ''
      split_keyword = keyword.split(/[[:blank:]]+/)
      @practices = []
      split_keyword.each do |keyword|
        next if keyword == ''

        @practices += Practice.where('title LIKE(?)', "%#{keyword}%")
      end
      @practices.uniq # 重複した商品を削除する
    end
  end

  # 通知機能（コメントといいね）

  # 自分がいいねしたときに、いいねした投稿、通知先、いいねしたというアクションを保存
  def create_notification_by(current_user)
    notification = current_user.active_notifications.new(practice_id: id, visited_id: user_id, action: 'like')
    notification.save if notification.valid?
  end

  def create_notification_comment!(current_user, pcomment_id, visited_id)
    # ある投稿に、あるコメントをしたユーザを登録する
    notification = current_user.active_notifications.new(
      practice_id: id,
      pcomment_id: pcomment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとして通知が来ないようにする
    notification.checked = true if notification.visiter_id == notification.visited_id
    notification.save if notification.valid?
  end
end

app/controllers/practices_controller.rb
class PracticesController < ApplicationController
  before_action :authenticate_user!, only: [:rank, :new, :show, :edit, :create, :update, :destroy, :search]
  before_action :set_practice, only: [:show, :destroy, :edit, :update]
  before_action :move_to_root, only: [:edit, :update, :destroy]

  def index
    @practices = Practice.includes(:user).order('created_at DESC').page(params[:page]).per(10)
    @like = Like.new
  end

  def show
    @pcomment = Pcomment.new
    @pcomments = Pcomment.order('created_at DESC').where(practice_id: @practice.id)
    @ptags = @practice.ptags
  end

  def new
    @practice = PracticesPtag.new
  end

  def create
    @practice = PracticesPtag.new(create_params)
    ptag_list = params[:practices_ptag][:name].split(',')

    if @practice.valid?
      flash[:notice] = '投稿に成功しました'
      @practice.save(ptag_list)
      redirect_to root_path
    else
      flash[:alert] = '投稿に失敗しました'
      render :new
    end
  end

  def edit
    @practices_ptag = PracticesPtag.new(title: @practice.title, content: @practice.content, category_id: @practice.category_id,
                                        hardlevel_id: @practice.hardlevel_id)
  end

  def update
    @practices_ptag = PracticesPtag.new(update_params)
    ptag_list = params[:practices_ptag][:name].split(',')
    if @practices_ptag.valid?
      flash[:notice] = '編集に成功しました'
      @practices_ptag.update(ptag_list)
      redirect_to practice_path(@practice)
    else
      flash[:alert] = '編集に失敗しました'
      render :edit
    end
  end

  def destroy
    if @practice.destroy
      flash[:notice] = '削除に成功しました'
      redirect_to root_path
    else
      flash[:alert] = '削除に失敗しました'
      redirect_to root_path
    end
  end

  def search
    @practices = Practice.search(params[:keyword])
  end

  def rank
    @practices = Practice.includes(:liked_users).limit(5).sort { |a, b| b.liked_users.size <=> a.liked_users.size }
  end

  def ptaglist
    return nil if params[:keyword] == ''

    ptag = Ptag.where(['name LIKE ?', "%#{params[:keyword]}%"])
    render json: { keyword: ptag }
  end

  private

  def create_params
    params.require(:practices_ptag).permit(:title, :content, :hardlevel_id, :name, :category_id,
                                           images: []).merge(user_id: current_user.id)
  end

  def update_params
    params.require(:practices_ptag).permit(:title, :content, :hardlevel_id, :name, :category_id, images: []).merge(
      user_id: current_user.id, practice_id: params[:id]
    )
  end

  def set_practice
    @practice = Practice.find(params[:id])
  end

  def move_to_root
    redirect_to root_path unless @practice.user.id == current_user.id
  end
end

app/helpers/practices_helper.rb
module PracticesHelper
end

app/views/practices/edit.html.erb
<% breadcrumb :practice_edit, @practice %>

<div class="main">
<div class="form_box">

  <h1 class="page-title">編集</h1>
<%= form_with model: @practices_ptag, url: practice_path(@practice),method: :patch,multipart: true,local: true do |f| %>
         <%=render 'partial/error_messages', model: f.object %>

         
        <div class="form-group">
          <label>タイトル</label>
          <%= f.text_field :title, autofocus: true, placeholder: "検索されやすいタイトルにしよう", class: "form-control" %>
        </div>

        <div class="form-group">
          <label>練習カテゴリー</label>
          <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box"}) %>
        </div>

        <div class="form-group">
          <label>練習の内容(現在の文字数：<span id="char-count"><%=@practices_ptag.content.length%></span>文字)</label>
          <%= f.text_area :content, autofocus: true,size: "20x10", placeholder: "例）この日は文化祭終了後だったので、短時間で高負荷のトレーニングを行いました。30メートル区間のダッシュを30本行い、1本毎のインターバルを10秒としました。選手からは相当きついとの声があり、、、", class: "form-control",id: "lesson-content" %>
        </div>


        <div class="form-group">
          <label>負荷のレベル</label>
          <%= f.collection_select(:hardlevel_id, Hardlevel.all, :id, :name, {}, {class:"select-box"}) %>
        </div>

        <div class="form-group">
          <label>タグ</label>
          <%= f.text_field :name, placeholder:",で区切ってください",class: "form-control" %>
        </div>
         <div id="search-result"></div>
       

        <div class="form-group">
          <label>練習風景の写真等（4枚までOK）</label><br>
          <%= f.file_field :images,id: "practice_image",multiple: true %>
        </div>
        <div id="practice-views"></div>

       
        <div class="actions">
          <%= f.submit "更新する", id: "submit",class: "btn btn-primary registration-btn" %>
        </div>
      <% end %>
</div>

    
 
</div>


<%= javascript_pack_tag 'count' %>
<%= javascript_pack_tag 'practice_preview' %>
<%= javascript_pack_tag 'ptag' %>

app/views/practices/index.html.erb
<% breadcrumb :root %>


<%= form_with(url: search_practices_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する(例：効率　面白い　最強)", class: "form-control search-input" %>
  <%= form.submit "検索", class: "btn btn-success search-btn" %>
<% end %>
<div class="to_ranking">
みんなが「いいね」した投稿は<%=link_to "こちら",rank_practices_path%>
</div>

<div class="contents">
 <%=render partial: 'partial/practice', collection: @practices %>
</div>


<div class="pagenation-box">
<%= paginate @practices %>
</div>

app/views/practices/new.html.erb
<div class="main">
<div class="form_box">

  <h1 class="page-title">練習を共有しよう</h1>
<%= form_with model: @practice, url: practices_path(@practice), multipart: true,local: true do |f| %>
         <%=render 'partial/error_messages', model: f.object %>

         
        <div class="form-group">
          <label>タイトル</label>
          <%= f.text_field :title, autofocus: true, placeholder: "検索されやすいタイトルにしよう！", class: "form-control" %>
        </div>

        <div class="form-group">
          <label>練習カテゴリー</label>
          <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box"}) %>
        </div>

        <div class="form-group">
          <label>練習の内容(現在の文字数：<span id="char-count">0</span>文字)</label>
          <%= f.text_area :content, autofocus: true,size: "20x10", placeholder: "例）この日は文化祭終了後だったので、短時間で高負荷のトレーニングを行いました。30メートル区間のダッシュを30本行い、1本毎のインターバルを10秒としました。選手からは相当きついとの声があり、、、", class: "form-control",id: "lesson-content" %>
        </div>


        <div class="form-group">
          <label>負荷のレベル</label>
          <%= f.collection_select(:hardlevel_id, Hardlevel.all, :id, :name, {}, {class:"select-box"}) %>
        </div>
        
        <div class="form-group">
          <label>タグ</label>
          <%= f.text_field :name, placeholder:",で区切ってください",class: "form-control" %>
        </div>
        <div id="search-result"></div>
     

        <div class="form-group">
          <label>練習風景の写真等（※4枚まで）</label><br>
          <%= f.file_field :images,name: 'practices_ptag[images][]' ,multiple: true,id:"practice_image"%>
        </div>

        <div id="practice-views"></div>

       
        <div class="actions">
          <%= f.submit "投稿する", id: "submit",class: "btn btn-primary registration-btn" %>
        </div>
      <% end %>
</div>

    
 
</div>


<% breadcrumb :practice_new %>

<%= javascript_pack_tag 'count' %>
<%= javascript_pack_tag 'practice_preview' %>
<%= javascript_pack_tag 'ptag' %>

app/views/practices/rank.html.erb
<% breadcrumb :rank%>


<div class="rank_title">
みんながいいね！した投稿
</div>

<div class="to_ranking">
一覧に<%=link_to "戻る",root_path%>
</div>

<div class="contents">
 <%=render partial: 'partial/practice', collection: @practices %>
</div>

<div class="back">
</div>

app/views/practices/search.html.erb
<% breadcrumb :search%>


<%= form_with(url: search_practices_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する(例：効率　面白い　最強)", class: "form-control search-input" %>
  <%= form.submit "検索", class: "btn btn-success search-btn" %>
<% end %>

<div class="to_ranking">
一覧に<%=link_to "戻る",root_path%>
</div>
<div class="contents">
<%if @practices==nil || @practices==[]%>
  <div class="no-result">
    <h4>検索結果は0件です</h4>
  </div>
<%else %>
 <%=render partial: 'partial/practice', collection: @practices %>
  
<%end%>
</div>

app/views/practices/show.html.erb
<% breadcrumb :practice_show, @practice %>

<div class="tweet_box">

  <div class="tweet_box__user"> <%#投稿上部の投稿者表示%>
    <div class="tweet_user">
      <div class="tweet_user__img">
         <%if @practice.user.myphoto.attached?%>
            <%=link_to (image_tag @practice.user.myphoto, class: "smround-img"),user_path(@practice.user)%>
         <%else%>
            <%=link_to (image_tag '/default_myphoto.png' , class: "smround-img"),user_path(@practice.user)%>
         <%end%>
      </div>
      <div class="tweet_user__name">
        <%=link_to "#{@practice.user.name}さんが投稿",user_path(@practice.user),class:"tweet_name"%>
      </div>
    </div>
  </div>
  
    <div class="tweet_box__img show_img" >
      <div class="slick-images">
        <%@practice.images.each do |image|%>
        <%=image_tag image ,class: "slider-img"%>
        <%end%>
      </div>
    </div>
 
  
  <div class="tweet_box__info"><%#練習詳細%>
    <div class="practice_info"><%#練習内容本文%>
      <p>練習の詳細</p>
      <div class="practice_text">
        <%=@practice.content%>
      </div>
      <div class="practice_info__content">
        <div class="hardlevel">
          <p>
            <i class="fas fa-dumbbell"></i> 負荷のレベル 
          </p>
          <p>
            <%=@practice.hardlevel.name%>
          </p>
        </div>
        <div class="category">
          <p>
            <i class="fas fa-futbol"></i> カテゴリー
          </p>
          <p>
            <%=@practice.category.name%>
          </p> 
        </div>
      </div>

    </div>

  </div>
  
  <div class="tweet_box__info">
    <div class="m tag_info">
       タグ:
      <%@ptags.each do |ptag|%>
       <%=ptag.name%>
      <%end%>
    </div>
    <div class="m tweet_box__flex">
      <div id="like-<%=@practice.id%>" class="m like_info">
        <%=render partial: 'likes/like',locals: {practice:@practice}%>
      </div>
      <div class="m created_at_info"><i class="far fa-clock clock-icon"></i><%= time_ago_in_words(@practice.created_at) %>前
      </div>
    </div>
  </div>
</div>

<%if current_user.id==@practice.user.id%>
  <div class="btn_field">
      <div class="btn-zone flex_reverse">
        <%= link_to "編集", edit_practice_path(@practice), method: :get, class: "btn btn-info" %>
        <%= link_to "戻る",root_path, method: :get, class: "btn btn-secondary" %>
      </div>
      <div class="delete_btn">
        <%= link_to "削除する", practice_path(@practice), method: :delete, class: "btn btn-danger",data: { confirm: '本当に削除しますか?' } %>
      </div>
  </div>

  
<%end%>


<div class="comments">
  <h2 class="comment_title">コメント</h2>
    <div class="comments__form">
      <div class="comments__input">
        <% if user_signed_in? %>
          <%= form_with(model: [@practice, @pcomment]) do |f| %>
            <%=render 'partial/error_messages', model: f.object %>
            <%= f.text_area :comment, placeholder: "※空のままではコメントできません", class: "form-control",rows: "4" %>
            <%= f.submit "コメントする",class:"btn btn-outline-success comment-btn" %>
          <% end %>
        <% end %>  
      </div>
    <div class="comment-line"></div>
      <div id="comments_box">
        
        <%= render partial: "partial/pcomment_box",collection:@pcomments,as: "pcomment",locals:{practice:@practice}%>
         
      </div>
  </div>
</div>